/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import { anyApi } from "convex/server";

export const api = anyApi;
export const internal = anyApi;
