/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

export declare const api: any;
export declare const internal: any;
